---
apiVersion: v1
kind: Service
metadata:
  name: usermicroservice-service
spec:
  selector:
    app: usermicroservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
